title: Coach Rye
description: Jack of All Trades. Master of Myself.

url: https://www.coachrye.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: coachrye
  twitter: coachrye34
  #facebook: brianmaierjr
  email: rye@coachrye.com
  linkedin: ryansalvanera

google_analytics: "UA-58263416-1"

disqus:
    shortname: coachrye
